### ISSUE TITLE
Triggers MKII User-defined Labels

### ISSUE THREAD

**Issue by dirkleas** [AScustomWorks/AS#10]
Feature Request: add an optional JSON configuration file (ala' Rack template.vcv) for specifying an array of user-defined label text values. Reasonable constraints on the number of characters, encodings, etc. expected as appropriate for enumerated labels.

**Comment by AScustomWorks** [comment]
Hi, this feature was considered but discarded because the json file would be relevant only for the user, and difficult if not impossible to keep in sync with patches, and other users own settings.
Imagine you have your custom label settings and you send me a patch, two things can happen:

-  I have a custom label settings too, I wouldn't see your patch with the proper labels, not good.
-  When loading your patch my settings are replaced with yours, not good.

Maybe this could be dealt with on the future, but who knows, if anything it would have it's place within a preset system in rack app (no plans for that that I know of yet).

Meanwhile, you can suggest a few labels generic enough to be useful to everybody so I can consider adding them to the module.

**Comment by dirkleas** [comment]
thoughtful consideration appreciated -- waiting for possible preset plumbing sounds reasonable

**Comment by JeffGreenlee42** [comment]
dirkleas,   
Understood,  I am not familiar with how these Json files are used.  So, I am just wondering,  You can save other values in a patch?  like levels and knob positions all kinds of Audio and digital  parameters... ,  but it does not allow you to save a text value (a limited sized character string) in a patch?   I know there are other Modules like a "notes"  module (where you can jot down notes for a patch)  and there is another module I recently discovered from "LOG"  collectoin that is called "Tidy Up Cables".  its got incoming and outgoing patch points in a single column of rows - inputs on the left, outputs on the right ,  and inbetween you can type in labels for each patch cable.  I guess the idea is that it helps identify each of  your cables.   So..... did that developer use something other than Json?  I would presume that if I saved a patch with his module in it,  and emailed it off to a friend, they would be able to open the same patch in Rack and see those same  saved text values?
