### ISSUE TITLE
DelayPlus with time modulation corrupts the waveform

### ISSUE THREAD

**Issue by AeonPragma** [AScustomWorks/AS#22]
Hi Alfredo,
Comparing the module DelayPlus and the fundamental Delay, considering also what i would expect, I think that the module DelayPlus under time modulation produces incorrect waveforms, compared to the clean ones produced by the fundamental one. Moreover, judging by eyes, appears to me that at high frequency the modulation is applied less smoothly compared to the fundamental one, as it passes from one extreme to the other skipping intermediate states. Attached is a patch where the alteration of waveforms is evident.
VCV Rack 0.6.0 Windows 10, AS Modules 0.6.6

Thank you for the awesome modules!

[DelayBug.zip](https://github.com/AScustomWorks/AS/files/1961263/DelayBug.zip)

**Comment by AScustomWorks** [comment]
Hi Aeon, indeed DelayPlus is based on Fundamental but even so, is not exactly the same. Since I made the modifications to this one, Fundamental had a couple of changes here and there too.
You are right about what you found out, and I knew it worked like that since the start but it turns out I like the quirky behavior as it reminds me of the PT2399 chip based delays.
