### ISSUE TITLE
FLOW not an issue

### ISSUE THREAD

**Issue by alto777** [AScustomWorks/AS#25]
hi Alfredo!

As I get deeper into Rack, I am learning to hear errors the way I would see them. I have become obsessed with the clicking that hard edges introduce. I just happened to grab your Flow module to see if it was some hard edges on another experiment, sure enough!

But the switch was a bit slow, so poking into your code I redid it at 0.02 volts / step. Closer to ON/OFF hard, but still no clicks.

I observe that you fade at 0.001 volts / step, this would be different speeds at different sample rates - I have some fade-in/fade-out that is also steps, not time,  dependent, but I will add "yet", even though I never use anything but 44100, the sample rate God intends us to use…

Anyway, I express thanks that you make your code openly available, it means a quick experiment can be done at the cost of reversing a bit of it, which in any case always teaches me something.

I am thinking that I should fade up/down all my gate signal outputs, that is take responsibility on my side for the hard edges. It isn't that hard. But almost no one does that, gates tend to be hard edged, so to speak. I wonder if you have an opinion. Frequently gates go into ADSRs and such like, where edges can be mitigated, and I certainly want to be able to have, for example, a full attack but man that clicking, now that I am aware of it, is ver annoying. Another option switch?

Also: I noted the on-off nature of Flow, fixed that for my experiment by using the OR of triggers created on the rising and falling edges of the control input. Hetrick Boolean for logic, and my own clock edge detector. Total fun.

alto777

**Comment by AScustomWorks** [comment]
Hi Robert!
The settings you can find on Flow switches are the ones I came up with after trying a lot of combinations, to make it work fine with CV and Audio signals, there's a compromise made as you found out, because of this:

Usually for CV signals(triggers and gates) you want the hard cut to happen so nothing sneaks in after the switch, on triggers and gates there are no clicks to be heard most of the time anyway and as you said, if present, it's controllable with an ADSR which is where usually this signals go to... so that's probably the reason you don't see a soft switch implemented in other modules.

Now, for the audio side of things if the switch cuts too fast you'll get audible clicks, even more noticeable when dealing with high frequency content(try with the change you made and you'll hear it).

So, I guess it all depends on what you are trying to accomplish and if it makes sense doing it different or not.

And yes, I believe that seeing how somebody else did things in code is the best way to learn new tricks and understand how things work, and even to come up with some ideas of your own... that's the nature of evolution. Sometimes you'll see ugly things too though hehe.

**Comment by alto777** [comment]
I'll close this non-issue with thanks and: if there is really anything ugly on the inside you have more than made up for it with the beauty you have on the outside.

a7
