### ISSUE TITLE
MIDI toggles on mixers require double on/off

### ISSUE THREAD

**Issue by paulrobertpine** [AScustomWorks/AS#45]
Hello, 

Love your modules thanks for all your hard work. 

Issue report: MIDI toggles (0-127 on/off) require double activation on mute switches. Should be 127=on, 0=0ff

However, I can also see the advantage of the way you implemented it; this way it can be "tapped" on/off, with a MIDI note for example

**Comment by AScustomWorks** [comment]
Hi Paul, thanks!
Just played with MIDI to test this and well, is not really a bug on the mixers mute switches because in Rack the led switch components are momentary type, not toggle.... and there's no way to change this behavior other than using a toggle switch component, which has it's own quirks, and no led light. 

Maybe your hardware has a configuration to change this? I tested this with a launchpad, configuring the pads in Automap app from toggle to momentary, and all worked as expected.

**Comment by paulrobertpine** [comment]
Thanks Freddy,

That makes sense, thanks for explaining.

Paul
