### ISSUE TITLE
AS Stereo Delay colour dials are non-operational when sends are in use

### ISSUE THREAD

**Issue by Amy-Triptyline** [AScustomWorks/AS#47]
This module is in every one of my patches, but one thing I've always wondered is: Is there any particular reason why the colour dials cease to operate when the send and returns are in use? I just can't see why this would be, it's slightly frustrating having to place filters on the end of both returns every time they are used...rather than just turning the dial.

**Comment by AScustomWorks** [comment]
Hi Amy!
The way the module works now is assuming you are indeed using the send/return ports to filter externally the wet (delayed) signal, which is the intended use, so you wouldn't want the internal filter to also affect this signal, right?

I get that you can process differently the send/return outputs, not only with a filter, but the module can't know what are you doing.

And this behavior is because the internal filter is just a band pass low/high filter, good enough for quick stuff but not comparable to what you can achieve with external filters.

Btw. I have 3 guitar floorboards with send/return ports for external distortion FXs/amps, and the 3 work exactly the same way, disabling the distortion section, so I'd assume this is an fx standard way of doing it.
Anyway, suggestions that won't break the original behavior are welcome ;)

**Comment by Amy-Triptyline** [comment]
Thanks for getting back to me I appreciate your time, actually I did wonder if hardware would also behave like this so you've answered that question too. So, I shall continue to put filters at the end of the send chain, no harm done :) Thanks for all your work on a fantastic set of modules.
