### ISSUE TITLE
Mixer mix slider does not work.

### ISSUE THREAD

**Issue by Euphorbium** [AScustomWorks/AS#52]
the mix slider of the rightmost mixer ( the last one before audio-8 module) does not work. What seems strange, is that sometimes, depending on some conditions it does work, but i don't know why. But it never works in the attached file on my machine.

[bug.vcv.zip](https://github.com/AScustomWorks/AS/files/3891622/bug.vcv.zip)

**Comment by AScustomWorks** [comment]
Hi Juozas, indeed, it doesn't work like that:
The MIX L & R inputs are not present on the master mix fader, just go directly to the outputs so you still need to control each mix fader... I'll see about implementing a switch so the user can change this behavior ;)

**Comment by Euphorbium** [comment]
I dont see the need for any kind of switch, the mixer slider works, when there is only one mixer, but does not work when there are more than one chained together.

**Comment by AScustomWorks** [comment]
The need for the switch would be to leave any patch using an old version of the mixer still working as it was.
"when there is only one mixer, but does not work when there are more than one chained together"
Yes, because it controls it's own internal channels, the MIX L & R inputs is only pass thru to avoid messing with the levels from other mixers. Think of each mixer like a sub group, you still have the overall control of each mixer by itself, but it won't affect other chained mixers (as it is now).

The get what you want (if I understand right) you would use one mixer as a master, connecting every other mixer to the internal channels of the master mixer (each pair of channels work as stereo pair, because of the pan control)
